version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${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}
    volumes:
      - ./backend:/app
    
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend